"""
Django settings for back_Store_django project.

Generated by 'django-admin startproject' using Django 5.2.
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'store-city.onrender.com',
    '*.onrender.com',
    'localhost',
    '127.0.0.1',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'store_db_qoyh'),
        'USER': os.getenv('PGUSER', 'store_db_qoyh_user'),
        'PASSWORD': os.getenv('PGPASSWORD', 'NDmRRjazpPDVhQXjnncFHDWIsI2NhGeL'),
        'HOST': os.getenv('PGHOST', 'dpg-d0m7a9ggjchc739k7i40-a.oregon-postgres.render.com'),
        'PORT': os.getenv('PGPORT', '5432'),
    }
}

CORS_ALLOWED_ORIGINS = [
    'https://store-city.vercel.app',
]

CSRF_TRUSTED_ORIGINS = [
    'https://store-city.onrender.com',
    'https://store-city.vercel.app',
]

STRIPE_SECRET_KEY = "sk_test_51RQJTjHBEtBDlMYRmWQgZrZosFVPabQHexlLxnH1n1NbWo0rfGWBmpAYpfaF0QtYb1looFhT1ZATSM8eRHonLpEE00t67EcxAt"
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "djoser",
    "product",
    "order",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://store-city.vercel.app",
]
CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS']

ROOT_URLCONF = "back_Store_django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "back_Store_django.wsgi.application"

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'store_db_qoyh'),
        'USER': os.getenv('PGUSER', 'store_db_qoyh_user'),
        'PASSWORD': os.getenv('PGPASSWORD', 'NDmRRjazpPDVhQXjnncFHDWIsI2NhGeL'),
        'HOST': os.getenv('PGHOST', 'dpg-d0m7a9ggjchc739k7i40-a.oregon-postgres.render.com'),
        'PORT': os.getenv('PGPORT', '5432'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}
